[project]
name = "django-container"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.8"
dependencies = [
    "granian>=2.5.5",
    "starlette>=0.48.0",
]
