FROM ghcr.io/astral-sh/uv:0.9.5-trixie-slim AS build
LABEL authors="codingjoe"

# Install dependencies
COPY ../../../Aptfile /tmp
RUN cd /tmp && apt-get update && cat Aptfile | xargs apt-get download \
    && mkdir -p /dpkg && \
    for deb in *.deb; do dpkg --extract $deb /dpkg || exit 10; done

RUN apt-get install -y curl git build-essential

ENV N_PREFIX=/opt/nodejs
ENV PATH=$N_PREFIX/bin:$PATH
ARG NODE_ENV=production
ENV NODE_ENV=$NODE_ENV

WORKDIR /app
COPY ../../../.nvmrc /app/.nvmrc
RUN curl -fsSL https://raw.githubusercontent.com/tj/n/master/bin/n | bash -s install --cleanup auto
RUN mkdir node_modules # In case there are no dependencies
RUN --mount=type=cache,target=/app/node_modules --mount=type=bind,source=../../../package-lock.json,target=package-lock.json --mount=type=bind,source=../../../package.json,target=package.json npm ci
COPY .. /app
RUN --mount=type=cache,target=/app/node_modules npm ci

FROM gcr.io/distroless/cc:nonroot AS development

# Copy binary dependencies
COPY --from=build /dpkg /

# Copy Node dependencies
COPY --from=build --chown=root:root /opt/nodejs /opt/nodejs
COPY --from=build --chown=root:root /app/node_modules /opt/node_modules

ENV NODE_PATH=/opt/node_modules
ENV PATH="/opt/nodejs/bin:$PATH"

EXPOSE 8000

WORKDIR /app

ENTRYPOINT ["node"]

FROM development AS production

COPY .. /app
