FROM caddy:2.10.0-alpine

RUN caddy add-package github.com/greenpau/caddy-security

ENV CADDY_AUTH_CLIENT_ID,=CADDY_AUTH_CLIENT_SECRET
ENV HOSTNAME=localhost

ARG TZ=UTC
ENV TZ=$TZ
COPY ./containers/caddy/Caddyfile /etc/caddy/Caddyfile
