FROM caddy:2.10.0-alpine
LABEL title="SMTP Server"
LABEL license="BSD-2-Clause"
LABEL url="https://github.com/codingjoe/freePaaS"

ENV HOSTNAME=localhost

RUN caddy add-package github.com/greenpau/caddy-security

COPY ./containers/caddy/Caddyfile /etc/caddy/Caddyfile
