name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:


concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
      - run: uvx pre-commit run --all-files --show-diff-on-failure
        env:
          SKIP: "no-commit-to-branch"

  container:
    name: Build containers
    runs-on: ubuntu-latest
    needs:
      - pre-commit
    strategy:
      fail-fast: true
      matrix:
        container-file:
          - Containerfile
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.container-file }}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
